name: Create jira ticket
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types: [opened]

jobs:  
  create-jira-ticket:
    runs-on: ubuntu-latest
    name: Create Jira Ticket
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12 #install the python needed
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: save issue body to file
      run: echo -e "${{ github.event.issue.body }}" > issue_body.txt && cat issue_body.txt
    - name: execute py script
      run: |
        python3 create_jira_ticket.py  --component "GitHub" --issue "${{ github.event.issue.number }}" \
          --github-html-url "${{ github.event.issue.html_url }}" --github-issue-title "${{ github.event.issue.title }}" \
          --github-issue-body-file issue_body.txt \
          --jira-user "${{ secrets.JIRA_USER }}" --jira-api-token "${{ secrets.JIRA_API_TOKEN }}" \
          --jira-api-url "${{ secrets.JIRA_API_URL }}"
    - name: cleanup
      run: rm issue_body.txt
    # TODO: add comment to issue with jira ticket number
    # - name: add comment to issue
      
