name: Create jira ticket
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types: [opened]

jobs:
  # get-issue:
  #   runs-on: ubuntu-latest
  #   # name: Print out issue information
  #   steps:
  #     - run: echo "Issue title: ${{ github.event.issue.title }}"
  #     - run: echo "Issue body: ${{ github.event.issue.body }}"
  #     - run: echo "Issue number: ${{ github.event.issue.number }}"
  #     - run: echo "Issue html_url: ${{ github.event.issue.html_url }}"

  
  create-jira-ticket:
    runs-on: ubuntu-latest
    name: Create Jira ticket
    steps:
    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12 #install the python needed
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: save issue body to file
      run: echo "${{ github.event.issue.body }}" > issue_body.txt && cat issue_body.txt
    - name: execute py script
      run: |
        python3 create_jira_ticket.py  --component "GitHub" --issue "${{ github.event.issue.number }}" \
          --github-html-url "${{ github.event.issue.html_url }}" --github-issue-title "${{ github.event.issue.title }}" \
          --github-issue-body-file issue_body.txt \
          --jira-user "${{ secrets.JIRA_USER }}" --jira-api-token "${{ secrets.JIRA_API_TOKEN }}" \
          --jira-api-url "${{ secrets.JIRA_API_URL }}"
