name: Create jira ticket
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issues:
    types: [opened]

jobs:
  get-issue:
    runs-on: ubuntu-latest
    name: Get issue info
    steps:
      - run: echo "Issue title ${{ github.event.issue.title }} event."
      - run: echo "Issue body ${{ github.event.issue.body }} event."
      - run: echo "Issue number ${{ github.event.issue.number }} event."

  
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 #install the python needed
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: execute py script
        run: |
          python create_jira_ticket.py -h
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
